version: "3.7"
services:

  python-cli:
    container_name: stripe-payment-python-cli
    image: romanr2/stripe-payment-python-cli:v1.0.1
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ../stripe-payment:/usr/src/app/
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres

  postgres:
    container_name: stripe-payment-postgres
    image: romanr2/stripe-payment-postgres:v1.0.1
    restart: always
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
    ports:
      - "54321:5432"
    env_file:
      - ./.env.prod.db

  nginx:
    container_name: stripe-payment-nginx
    image: romanr2/stripe-payment-nginx:v1.0.1
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:80"
    depends_on:
      - python-cli

volumes:
  postgres-volume:
  static_volume: