version: "3.7"
services:

  python-cli:
    container_name: stripe-payment-python-cli
    build:
      context: ./
      dockerfile: ./docker/development/python-cli.docker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../stripe-payment:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

  postgres:
    container_name: stripe-payment-postgres
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
    ports:
      - "54321:5432"

volumes:
  postgres-volume: